In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
items_categories = pd.read_csv('item_categories.csv')
sales_train = pd.read_csv('sales_train.csv')
items = pd.read_csv('items.csv')
sample_submission = pd.read_csv('sample_submission.csv')
shops = pd.read_csv('shops.csv')
test = pd.read_csv('test.csv')

In [4]:
items_categories.head()

        item_category_name  item_category_id
0  PC - Гарнитуры/Наушники                 0
1         Аксессуары - PS2                 1
2         Аксессуары - PS3                 2
3         Аксессуары - PS4                 3
4         Аксессуары - PSP                 4

In [5]:
sales_train.head()

         date  date_block_num  shop_id  item_id  item_price  item_cnt_day
0  02.01.2013               0       59    22154      999.00           1.0
1  03.01.2013               0       25     2552      899.00           1.0
2  05.01.2013               0       25     2552      899.00          -1.0
3  06.01.2013               0       25     2554     1709.05           1.0
4  15.01.2013               0       25     2555     1099.00           1.0

In [6]:
items.head()

,item_name,item_id,item_category_id
0,! ВО ВЛАСТИ НАВАЖДЕНИЯ (ПЛАСТ.) D,0,40
1,!ABBYY FineReader 12 Professional Edition Full...,1,76
2,***В ЛУЧАХ СЛАВЫ (UNV) D,2,40
3,***ГОЛУБАЯ ВОЛНА (Univ) D,3,40
4,***КОРОБКА (СТЕКЛО) D,4,40

In [7]:
sample_submission.head()

   ID  item_cnt_month
0   0             0.5
1   1             0.5
2   2             0.5
3   3             0.5
4   4             0.5

In [8]:
shops.head()

                        shop_name  shop_id
0   !Якутск Орджоникидзе, 56 фран        0
1   !Якутск ТЦ "Центральный" фран        1
2                Адыгея ТЦ "Мега"        2
3  Балашиха ТРК "Октябрь-Киномир"        3
4        Волжский ТЦ "Волга Молл"        4

In [9]:
test.head()

   ID  shop_id  item_id
0   0        5     5037
1   1        5     5320
2   2        5     5233
3   3        5     5232
4   4        5     5268

In [10]:
df = sales_train.merge(items, on='item_id', how='left')

In [11]:
df = df.merge(items_categories, on='item_category_id', how='left')

In [12]:
df = df.merge(shops, on='shop_id', how='left')

In [13]:
df.head()

,date,date_block_num,shop_id,item_id,item_price,item_cnt_day,item_name,item_category_id,item_category_name,shop_name
0,02.01.2013,0,59,22154,999.00,1.0,ЯВЛЕНИЕ 2012 (BD),37,Кино - Blu-Ray,"Ярославль ТЦ ""Альтаир"""
1,03.01.2013,0,25,2552,899.00,1.0,DEEP PURPLE The House Of Blue Light LP,58,Музыка - Винил,"Москва ТРК ""Атриум"""
2,05.01.2013,0,25,2552,899.00,-1.0,DEEP PURPLE The House Of Blue Light LP,58,Музыка - Винил,"Москва ТРК ""Атриум"""
3,06.01.2013,0,25,2554,1709.05,1.0,DEEP PURPLE Who Do You Think We Are LP,58,Музыка - Винил,"Москва ТРК ""Атриум"""
4,15.01.2013,0,25,2555,1099.00,1.0,DEEP PURPLE 30 Very Best Of 2CD (Фирм.),56,Музыка - CD фирменного производства,"Москва ТРК ""Атриум"""

### Проверка качества данных

In [14]:
df['item_cnt_day'].value_counts()

item_cnt_day
1.0       2629372
2.0        194201
3.0         47350
4.0         19685
5.0         10474
           ...
251.0           1
501.0           1
112.0           1
164.0           1
2169.0          1
Name: count, Length: 198, dtype: int64

In [15]:
df.isnull().sum()

date                  0
date_block_num        0
shop_id               0
item_id               0
item_price            0
item_cnt_day          0
item_name             0
item_category_id      0
item_category_name    0
shop_name             0
dtype: int64

In [16]:
df.duplicated().sum()

6

In [17]:
df = df.drop_duplicates()

In [18]:
print(df['date'].dtype)

object

In [19]:
df['date'] = pd.to_datetime(df['date'], format='%d.%m.%Y')
print(df['date'].dtype)

datetime64[ns]

In [20]:
df.head()

,date,date_block_num,shop_id,item_id,item_price,item_cnt_day,item_name,item_category_id,item_category_name,shop_name
0,2013-01-02,0,59,22154,999.00,1.0,ЯВЛЕНИЕ 2012 (BD),37,Кино - Blu-Ray,"Ярославль ТЦ ""Альтаир"""
1,2013-01-03,0,25,2552,899.00,1.0,DEEP PURPLE The House Of Blue Light LP,58,Музыка - Винил,"Москва ТРК ""Атриум"""
2,2013-01-05,0,25,2552,899.00,-1.0,DEEP PURPLE The House Of Blue Light LP,58,Музыка - Винил,"Москва ТРК ""Атриум"""
3,2013-01-06,0,25,2554,1709.05,1.0,DEEP PURPLE Who Do You Think We Are LP,58,Музыка - Винил,"Москва ТРК ""Атриум"""
4,2013-01-15,0,25,2555,1099.00,1.0,DEEP PURPLE 30 Very Best Of 2CD (Фирм.),56,Музыка - CD фирменного производства,"Москва ТРК ""Атриум"""

In [21]:
df['date'] = pd.to_datetime(df['date'])
df = df.sort_values('date').reset_index(drop=True)

In [22]:
df.head()

,date,date_block_num,shop_id,item_id,item_price,item_cnt_day,item_name,item_category_id,item_category_name,shop_name
0,2013-01-01,0,18,16182,1619.0,1.0,Настольная игра Монополия арт. 00009H,64,Подарки - Настольные игры,"Красноярск ТЦ ""Июнь"""
1,2013-01-01,0,54,12355,399.0,1.0,КАК ПО МАСЛУ,40,Кино - DVD,"Химки ТЦ ""Мега"""
2,2013-01-01,0,54,16877,149.0,1.0,ПАРАНОРМАЛЬНОЕ ЯВЛЕНИЕ (регион),40,Кино - DVD,"Химки ТЦ ""Мега"""
3,2013-01-01,0,27,15435,499.0,1.0,Мягкая игрушка СОЮЗМУЛЬТФИЛЬМ Бонифаций,63,Подарки - Мягкие игрушки,"Москва ТЦ ""МЕГА Белая Дача II"""
4,2013-01-01,0,54,19678,149.0,1.0,ТИТАНИК (регион),40,Кино - DVD,"Химки ТЦ ""Мега"""

In [23]:
df['sales_yesterday'] = df.groupby(['shop_id', 'item_id'])['item_cnt_day'].shift(1)

In [24]:
df['sales_last_week'] = df.groupby(['shop_id', 'item_id'])['item_cnt_day'].shift(7)

In [25]:
df['sales_last_month'] = df.groupby(['shop_id', 'item_id'])['item_cnt_day'].shift(30)

In [26]:
df.head()

,date,date_block_num,shop_id,item_id,item_price,item_cnt_day,item_name,item_category_id,item_category_name,shop_name,sales_yesterday,sales_last_week,sales_last_month
0,2013-01-01,0,18,16182,1619.0,1.0,Настольная игра Монополия арт. 00009H,64,Подарки - Настольные игры,"Красноярск ТЦ ""Июнь""",NaN,NaN,NaN
1,2013-01-01,0,54,12355,399.0,1.0,КАК ПО МАСЛУ,40,Кино - DVD,"Химки ТЦ ""Мега""",NaN,NaN,NaN
2,2013-01-01,0,54,16877,149.0,1.0,ПАРАНОРМАЛЬНОЕ ЯВЛЕНИЕ (регион),40,Кино - DVD,"Химки ТЦ ""Мега""",NaN,NaN,NaN
3,2013-01-01,0,27,15435,499.0,1.0,Мягкая игрушка СОЮЗМУЛЬТФИЛЬМ Бонифаций,63,Подарки - Мягкие игрушки,"Москва ТЦ ""МЕГА Белая Дача II""",NaN,NaN,NaN
4,2013-01-01,0,54,19678,149.0,1.0,ТИТАНИК (регион),40,Кино - DVD,"Химки ТЦ ""Мега""",NaN,NaN,NaN